# Generated by Django 5.1.2 on 2025-05-03 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amc_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('amc_doc_no', models.CharField(max_length=100)),
                ('amc_category', models.CharField(choices=[('Service AMC', 'Service AMC'), ('Labor AMC', 'Labor AMC')], max_length=20)),
                ('starting_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renew_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('number_of_services', models.PositiveIntegerField(default=1)),
                ('gst_number', models.CharField(blank=True, max_length=50, null=True)),
                ('terms_and_conditions', models.TextField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('google_map_url', models.URLField(blank=True, null=True)),
                ('amc_notes', models.TextField(blank=True, null=True)),
                ('services_notes', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amcs', to='admins.customer')),
            ],
            options={
                'verbose_name': 'AMC',
                'verbose_name_plural': 'AMCs',
            },
        ),
    ]
