# Generated by Django 5.1.2 on 2025-05-03 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='amc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='admins.amc'),
        ),
    ]
