# Generated by Django 5.1.2 on 2025-05-12 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_call_amc'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSheet',
            fields=[
                ('job_sheet_no', models.AutoField(primary_key=True, serialize=False)),
                ('contact_number', models.CharField(max_length=15)),
                ('model_name_or_number', models.CharField(blank=True, max_length=255, null=True)),
                ('emi_or_serial_or_part_number', models.CharField(blank=True, max_length=255, null=True)),
                ('physical_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('problem', models.TextField(blank=True, null=True)),
                ('accessories', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('terms_and_conditions', models.TextField(default='Default')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_sheets', to='admins.customer')),
                ('executives', models.ManyToManyField(related_name='job_sheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
