# Generated by Django 5.1.2 on 2025-05-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_customer_call_status_customer_closed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='call_status',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='closed_at',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='reason',
        ),
        migrations.AddField(
            model_name='call',
            name='call_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='call',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
