# Generated by Django 5.1.2 on 2025-05-28 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_jobsheet_closed_at_jobsheet_job_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobsheet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
